name: docker build & registry push (latest)

on:
  create:
    tags: 'v*'

jobs:
  release:
     runs-on: ubuntu-latest
     steps:

     - name: Checkout
       uses: actions/checkout@v1
     
     - name: Dockerhub login
       env:
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       run: echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
     
     - name: Set up Docker Buildx
       id: buildx
       uses: crazy-max/ghaction-docker-buildx@v1
       with:
         buildx-version: latest
     
     - name: Build and push image with all platforms binaries
       run: docker buildx build -t fabiolune/nginx-custom-backend:build -f Dockerfile --push .
     
     - name: Build and push multi arch runnable image
       run: |
         if [[ ${GITHUB_REF} == *"refs/tags"* ]]; 
         then
           VERSION=${GITHUB_REF#/refs/tags}
           VERSION=${VERSION#refs/tags}
           VERSION=${VERSION#v}
           docker buildx build --platform=linux/arm/v7,linux/arm64/v8,linux/amd64 -t fabiolune/nginx-custom-backend:latest -t fabiolune/nginx-custom-backend:${VERSION} -f publish.Dockerfile --push .
         else 
           docker buildx build --platform=linux/arm/v7,linux/arm64/v8,linux/amd64 -t fabiolune/nginx-custom-backend:latest -f publish.Dockerfile --push .
         fi

     - name: delete build base image from docker hub
       env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       run: docker run --rm fabiolune/dockerhub-image-remover:0.1.0 ${DOCKER_USERNAME} ${DOCKER_PASSWORD} fabiolune/nginx-custom-backend build
          
